package edu.scu.my_shop.entity;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.user_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone_number
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_info
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String addressInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_id
     *
     * @return the value of address.address_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_id
     *
     * @param addressId the value for address.address_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId == null ? null : addressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.user_id
     *
     * @return the value of address.user_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.user_id
     *
     * @param userId the value for address.user_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone_number
     *
     * @return the value of address.phone_number
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone_number
     *
     * @param phoneNumber the value for address.phone_number
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_info
     *
     * @return the value of address.address_info
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getAddressInfo() {
        return addressInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_info
     *
     * @param addressInfo the value for address.address_info
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setAddressInfo(String addressInfo) {
        this.addressInfo = addressInfo == null ? null : addressInfo.trim();
    }
}