package edu.scu.my_shop.entity;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbg.generated Mon Mar 19 15:05:08 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.totals
     *
     * @mbg.generated Mon Mar 19 15:05:08 CST 2018
     */
    private Integer totals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.product_id
     *
     * @mbg.generated Mon Mar 19 15:05:08 CST 2018
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_id
     *
     * @return the value of cart.user_id
     *
     * @mbg.generated Mon Mar 19 15:05:08 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_id
     *
     * @param userId the value for cart.user_id
     *
     * @mbg.generated Mon Mar 19 15:05:08 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.totals
     *
     * @return the value of cart.totals
     *
     * @mbg.generated Mon Mar 19 15:05:08 CST 2018
     */
    public Integer getTotals() {
        return totals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.totals
     *
     * @param totals the value for cart.totals
     *
     * @mbg.generated Mon Mar 19 15:05:08 CST 2018
     */
    public void setTotals(Integer totals) {
        this.totals = totals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.product_id
     *
     * @return the value of cart.product_id
     *
     * @mbg.generated Mon Mar 19 15:05:08 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.product_id
     *
     * @param productId the value for cart.product_id
     *
     * @mbg.generated Mon Mar 19 15:05:08 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }
}