package edu.scu.my_shop.entity;

public class FirstCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column first_category.first_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String firstCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column first_category.first_category_name
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String firstCategoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column first_category.first_category_id
     *
     * @return the value of first_category.first_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getFirstCategoryId() {
        return firstCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column first_category.first_category_id
     *
     * @param firstCategoryId the value for first_category.first_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setFirstCategoryId(String firstCategoryId) {
        this.firstCategoryId = firstCategoryId == null ? null : firstCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column first_category.first_category_name
     *
     * @return the value of first_category.first_category_name
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getFirstCategoryName() {
        return firstCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column first_category.first_category_name
     *
     * @param firstCategoryName the value for first_category.first_category_name
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setFirstCategoryName(String firstCategoryName) {
        this.firstCategoryName = firstCategoryName == null ? null : firstCategoryName.trim();
    }
}