package edu.scu.my_shop.entity;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.product_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_url
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String imageUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_id
     *
     * @return the value of image.image_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_id
     *
     * @param imageId the value for image.image_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.product_id
     *
     * @return the value of image.product_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.product_id
     *
     * @param productId the value for image.product_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_url
     *
     * @return the value of image.image_url
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_url
     *
     * @param imageUrl the value for image.image_url
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }
}