package edu.scu.my_shop.entity;

public class OrderItem extends OrderItemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_count
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private Integer productCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_count
     *
     * @return the value of order_item.product_count
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_count
     *
     * @param productCount the value for order_item.product_count
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }
}