package edu.scu.my_shop.entity;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.second_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String secondCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_price
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private Double productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_description
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String productDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_left_totals
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private Integer productLeftTotals;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.second_category_id
     *
     * @return the value of product.second_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getSecondCategoryId() {
        return secondCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.second_category_id
     *
     * @param secondCategoryId the value for product.second_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setSecondCategoryId(String secondCategoryId) {
        this.secondCategoryId = secondCategoryId == null ? null : secondCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_price
     *
     * @return the value of product.product_price
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public Double getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_price
     *
     * @param productPrice the value for product.product_price
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_description
     *
     * @return the value of product.product_description
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_description
     *
     * @param productDescription the value for product.product_description
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription == null ? null : productDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_left_totals
     *
     * @return the value of product.product_left_totals
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public Integer getProductLeftTotals() {
        return productLeftTotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_left_totals
     *
     * @param productLeftTotals the value for product.product_left_totals
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setProductLeftTotals(Integer productLeftTotals) {
        this.productLeftTotals = productLeftTotals;
    }
}