package edu.scu.my_shop.entity;

public class SecondCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.second_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String secondCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.first_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String firstCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.second_category_name
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    private String secondCategoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.second_category_id
     *
     * @return the value of second_category.second_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getSecondCategoryId() {
        return secondCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.second_category_id
     *
     * @param secondCategoryId the value for second_category.second_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setSecondCategoryId(String secondCategoryId) {
        this.secondCategoryId = secondCategoryId == null ? null : secondCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.first_category_id
     *
     * @return the value of second_category.first_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getFirstCategoryId() {
        return firstCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.first_category_id
     *
     * @param firstCategoryId the value for second_category.first_category_id
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setFirstCategoryId(String firstCategoryId) {
        this.firstCategoryId = firstCategoryId == null ? null : firstCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.second_category_name
     *
     * @return the value of second_category.second_category_name
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public String getSecondCategoryName() {
        return secondCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.second_category_name
     *
     * @param secondCategoryName the value for second_category.second_category_name
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    public void setSecondCategoryName(String secondCategoryName) {
        this.secondCategoryName = secondCategoryName == null ? null : secondCategoryName.trim();
    }
}