package edu.scu.my_shop.dao;

import edu.scu.my_shop.entity.FirstCategory;
import edu.scu.my_shop.entity.FirstCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirstCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    long countByExample(FirstCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int deleteByExample(FirstCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int deleteByPrimaryKey(String firstCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int insert(FirstCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int insertSelective(FirstCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    List<FirstCategory> selectByExample(FirstCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    FirstCategory selectByPrimaryKey(String firstCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") FirstCategory record, @Param("example") FirstCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int updateByExample(@Param("record") FirstCategory record, @Param("example") FirstCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int updateByPrimaryKeySelective(FirstCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int updateByPrimaryKey(FirstCategory record);
}