package edu.scu.my_shop.dao;

import edu.scu.my_shop.entity.SecondCategory;
import edu.scu.my_shop.entity.SecondCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    long countByExample(SecondCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int deleteByExample(SecondCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int deleteByPrimaryKey(String secondCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int insert(SecondCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int insertSelective(SecondCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    List<SecondCategory> selectByExample(SecondCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    SecondCategory selectByPrimaryKey(String secondCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") SecondCategory record, @Param("example") SecondCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int updateByExample(@Param("record") SecondCategory record, @Param("example") SecondCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int updateByPrimaryKeySelective(SecondCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Sat Mar 17 10:46:26 CST 2018
     */
    int updateByPrimaryKey(SecondCategory record);
}